package handler

// concelhosList is the complete list of Portuguese municipalities (concelhos).
// Sourced from official DGAL/INE data; update if administrative boundaries change.
var concelhosList = []string{
	"Abrantes", "Aguiar da Beira", "Alandroal", "Albergaria-a-Velha", "Albufeira",
	"Alcácer do Sal", "Alcanena", "Alcochete", "Alcoutim", "Alenquer",
	"Alfândega da Fé", "Algarve", "Alijó", "Aljezur", "Aljustrel",
	"Almada", "Almeida", "Almeirim", "Almodôvar", "Alpiarça",
	"Alter do Chão", "Alvaiázere", "Alvito", "Amadora", "Amarante",
	"Amares", "Anadia", "Angra do Heroísmo", "Ansião", "Arcos de Valdevez",
	"Arganil", "Armamar", "Arouca", "Arraiolos", "Arronches",
	"Arruda dos Vinhos", "Aveiro", "Avis", "Azambuja", "Baião",
	"Barcelos", "Barrancos", "Barreiro", "Batalha", "Beja",
	"Belmonte", "Benavente", "Bombarral", "Borba", "Boticas",
	"Braga", "Bragança", "Cabeceiras de Basto", "Cadaval", "Caldas da Rainha",
	"Caminha", "Campo Maior", "Cantanhede", "Carrazeda de Ansiães", "Carregal do Sal",
	"Cartaxo", "Cascais", "Castanheira de Pêra", "Castelo Branco", "Castelo de Paiva",
	"Castelo de Vide", "Castro Daire", "Castro Marim", "Castro Verde", "Celorico da Beira",
	"Celorico de Basto", "Chamusca", "Chaves", "Cinfães", "Coimbra",
	"Condeixa-a-Nova", "Constância", "Coruche", "Covilhã", "Crato",
	"Cuba", "Elvas", "Entroncamento", "Espinho", "Esposende",
	"Estarreja", "Estremoz", "Évora", "Fafe", "Faro",
	"Felgueiras", "Ferreira do Alentejo", "Ferreira do Zêzere", "Figueira da Foz", "Figueira de Castelo Rodrigo",
	"Figueiró dos Vinhos", "Fornos de Algodres", "Freixo de Espada à Cinta", "Fronteira", "Fundão",
	"Gavião", "Góis", "Golegã", "Gondomar", "Gouveia",
	"Grândola", "Guarda", "Guimarães", "Idanha-a-Nova", "Ílhavo",
	"Lagoa", "Lagos", "Lamego", "Leiria", "Lisboa",
	"Loulé", "Loures", "Lourinhã", "Lousã", "Lousada",
	"Macedo de Cavaleiros", "Mafra", "Maia", "Manteigas", "Marco de Canaveses",
	"Marinha Grande", "Marvão", "Matosinhos", "Mealhada", "Meda",
	"Melgaço", "Mesão Frio", "Mértola", "Mêda", "Miranda do Corvo",
	"Miranda do Douro", "Mirandela", "Mogadouro", "Moimenta da Beira", "Moita",
	"Monção", "Monchique", "Mondim de Basto", "Monforte", "Montalegre",
	"Montemor-o-Novo", "Montemor-o-Velho", "Montijo", "Mora", "Mortágua",
	"Moura", "Mourão", "Murça", "Murtosa", "Nazaré",
	"Nelas", "Nisa", "Óbidos", "Odivelas", "Oeiras",
	"Oleiros", "Olhão", "Oliveira de Azeméis", "Oliveira de Frades", "Oliveira do Bairro",
	"Oliveira do Hospital", "Ourém", "Ourique", "Ovar", "Paços de Ferreira",
	"Palmela", "Pampilhosa da Serra", "Paredes", "Paredes de Coura", "Pedrógão Grande",
	"Penacova", "Penafiel", "Penalva do Castelo", "Penamacor", "Penedono",
	"Penela", "Peniche", "Peso da Régua", "Pinhel", "Pombal",
	"Ponte da Barca", "Ponte de Lima", "Ponte de Sor", "Portalegre", "Portel",
	"Portimão", "Porto", "Porto de Mós", "Póvoa de Lanhoso", "Póvoa de Varzim",
	"Proença-a-Nova", "Redondo", "Reguengos de Monsaraz", "Resende", "Ribeira de Pena",
	"Rio Maior", "Sabrosa", "Sabugal", "Salvaterra de Magos", "Santa Comba Dão",
	"Santa Maria da Feira", "Santa Marta de Penaguião", "Santarém", "Santiago do Cacém", "Santo Tirso",
	"São Brás de Alportel", "São João da Madeira", "São João da Pesqueira", "São Pedro do Sul", "São Roque do Pico",
	"Sardoal", "Sátão", "Seia", "Seixal", "Sernancelhe",
	"Serpa", "Sertã", "Sesimbra", "Setúbal", "Sever do Vouga",
	"Silves", "Sines", "Sintra", "Soure", "Sousel",
	"Tábua", "Tabuaço", "Tarouca", "Tavira", "Terras de Bouro",
	"Tomar", "Tondela", "Torre de Moncorvo", "Torres Novas", "Torres Vedras",
	"Trancoso", "Trofa", "Vagos", "Vale de Cambra", "Valença",
	"Valongo", "Valpaços", "Vendas Novas", "Viana do Alentejo", "Viana do Castelo",
	"Vidigueira", "Vieira do Minho", "Vila de Rei", "Vila do Bispo", "Vila do Conde",
	"Vila Flor", "Vila Franca de Xira", "Vila Nova da Barquinha", "Vila Nova de Cerveira", "Vila Nova de Famalicão",
	"Vila Nova de Foz Côa", "Vila Nova de Gaia", "Vila Nova de Paiva", "Vila Nova de Poiares", "Vila Pouca de Aguiar",
	"Vila Real", "Vila Real de Santo António", "Vila Velha de Ródão", "Vila Verde", "Vila Viçosa",
	"Vimioso", "Vinhais", "Viseu", "Vizela", "Vouzela",
}
